services:
    postgres:
        image: postgres:17
        container_name: source_db
        restart: always
        ports:
            - "5432:5432"
        command: >
            postgres
            -c wal_level=logical
        environment:
            - POSTGRES_USER=cdc_user
            - POSTGRES_PASSWORD=cdc_password
            - POSTGRES_DB=cdc_db
        volumes:
            - ./docker_data/postgres:/var/lib/postgresql/data
            - ./scripts/init-postgres.sh:/docker-entrypoint-initdb.d/init-postgres.sh
        networks:
            - cdc-network

    schema-registry:
        image: confluentinc/cp-schema-registry:7.9.0
        hostname: schema-registry
        container_name: schema-registry
        depends_on:
            - zookeeper
        ports:
            - "8181:8181"
        environment:
            SCHEMA_REGISTRY_HOST_NAME: schema-registry
            SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
            SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:29092
        restart: on-failure
        networks:
            - cdc-network

    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        container_name: zookeeper
        restart: always
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
        ports:
            - "2181:2181"
        networks:
            - cdc-network

    kafka:
        image: confluentinc/cp-kafka:latest
        container_name: kafka
        restart: always
        ports:
            - "9092:9092"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
            KAFKA_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        depends_on:
            - zookeeper
        networks:
            - cdc-network

networks:
    cdc-network:
        external: true
